# Setup
title:               Dead Simple Auth
tagline:             ''
description:         'Making authenticating humans dead simple'
url:                 https://deadsimpleauth.github.io
baseurl:             ''
paginate:            5
permalink:           pretty
theme:               jekyll-theme-minimal

# About/contact
author:
  name:              Benjamin Hering
  url:               https://blog.benjamin-hering.com
  email:             inbox@benjamin-hering.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
github:
  repo:         'https://github.com/deadsimpleauth'

theme: jekyll-theme-minimal